backend:
  name: proxy
  proxy_url: http://173.249.49.45:9050/cms/proxy
  branch: main
  repo: hello-snamy/staticpages  # Repository where content is stored

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
